CREATE TABLE IF NOT EXISTS `mcp` (
    `key` VARCHAR(250) NOT NULL PRIMARY KEY,
    `value` JSON NOT NULL,
    `id` VARCHAR(150) GENERATED ALWAYS AS (value ->> '$.id') STORED NOT NULL,
    `namespace` VARCHAR(150) GENERATED ALWAYS AS (value ->> '$.namespace') STORED,
    `tenant_id` VARCHAR(150) GENERATED ALWAYS AS (value ->> '$.tenantId') STORED,
    `name` VARCHAR(250) GENERATED ALWAYS AS (value ->> '$.name') STORED,
    `description` TEXT GENERATED ALWAYS AS (value ->> '$.description') STORED,
    `system_prompt` TEXT GENERATED ALWAYS AS (value ->> '$.systemPrompt') STORED,
    `server_type` VARCHAR(50) GENERATED ALWAYS AS (value ->> '$.serverType') STORED,
    `auth_type` VARCHAR(50) GENERATED ALWAYS AS (value ->> '$.authType') STORED,
    `enabled` BOOL GENERATED ALWAYS AS (value ->> '$.enabled' = 'true') STORED,
    `icon_url` VARCHAR(500) GENERATED ALWAYS AS (value ->> '$.iconUrl') STORED,
    `is_default` BOOL GENERATED ALWAYS AS (value ->> '$.isDefault' = 'true') STORED,
    `deleted` BOOL GENERATED ALWAYS AS (value ->> '$.deleted' = 'true') STORED NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX ix_deleted_tenant (deleted, tenant_id),
    INDEX ix_id_deleted_tenant (id, deleted, tenant_id),
    INDEX ix_namespace_deleted_tenant (namespace, deleted, tenant_id),
    INDEX ix_enabled_deleted_tenant (enabled, deleted, tenant_id),
    FULLTEXT ix_fulltext (name)
) ENGINE INNODB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
